# Generated by Django 5.2.7 on 2025-10-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym_user',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gym_user',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
