# Generated by Django 5.2.6 on 2025-10-03 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0002_gym_user_is_blocked_gym_user_reminder_sent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dietplan',
            old_name='calories',
            new_name='total_calories',
        ),
        migrations.RemoveField(
            model_name='dietplan',
            name='meal_plan',
        ),
        migrations.RemoveField(
            model_name='workoutplan',
            name='exercises',
        ),
        migrations.CreateModel(
            name='DietDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_name', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=20)),
                ('breakfast', models.TextField()),
                ('lunch', models.TextField()),
                ('dinner', models.TextField()),
                ('snacks', models.TextField(blank=True, null=True)),
                ('diet_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_days', to='gym_app.dietplan')),
            ],
            options={
                'ordering': ['day_name'],
                'unique_together': {('diet_plan', 'day_name')},
            },
        ),
        migrations.CreateModel(
            name='WorkoutDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_name', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=20)),
                ('exercises', models.TextField(help_text='Enter exercises (one per line with sets/reps)')),
                ('notes', models.TextField(blank=True, null=True)),
                ('workout_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_days', to='gym_app.workoutplan')),
            ],
            options={
                'ordering': ['day_name'],
                'unique_together': {('workout_plan', 'day_name')},
            },
        ),
    ]
